name: Make release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version in semver (e.g. '0.5.0')
        required: true

jobs:
  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    needs:
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup environment
        run: |
          . ./hack/ci/setup-env.sh
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{env.GO_VERSION}}
      - name: Run K8s Controller integration tests
        run: |
          make test-k8s-controller
      - name: Get Capact CLI for linux
        run: |
          curl -Lo ./capact https://storage.googleapis.com/capactio-binaries/latest/capact-linux-amd64
          chmod +x ./capact
      - name: Run cross-functional integration tests
        env:
          BUILD_IMAGES: "false"
          ARTIFACTS: "output/"
          DISABLE_MONITORING_INSTALLATION: "true"
          CAPACT_BINARY: "./capact"
        run: |
          make test-integration
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: cluster_dump_${{github.sha}}
          path: "output"
          retention-days: 1

  make-release:
    name: Make release
    runs-on: ubuntu-latest
    needs: ["integration-tests"]
    environment: Release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Create release commit and tag
        env:
          RELEASE_VERSION: "${{ github.event.inputs.version }}"
        run: |
          git remote remove origin
          git remote add origin https://${{secrets.PAT}}@github.com/${{github.repository}}.git
          ./hack/create-release.sh
