name: Make release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version in semver (e.g. '0.5.0')
        required: true

jobs:
  make-release:
    name: Make release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Create release commit and tag
        env:
          RELEASE_VERSION: "${{ github.event.inputs.version }}"
        run: |
          ./hack/create-release.sh
