name: Create release

# When a tagged version commit is pushed, then this workflow creates GitHub release
# and publishes the binaries.

on:
  push:
    tags:
      - v*

jobs:
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:      
          fetch-depth: 0
      - name: Setup environment
        run: |
          . ./hack/ci/setup-env.sh
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{env.GO_VERSION}}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: v0.175.0
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
